# fly.toml for core-test app (demo server)

app = "core-tmp"
primary_region = 'ewr'

[build]
  dockerfile = "Dockerfile.demo"

[env]
  PORT = '8080'
  DISABLE_AUTH = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
