help:
	@echo "Available targets:"
	@echo "  === COMPREHENSIVE TESTING (default) ==="
	@echo "  all              - Clean, format, vet, lint, test, and scenarios"
	@echo "  test             - Run unit + local + deployed tests (comprehensive)"
	@echo "  unit-test        - Run unit tests with coverage"
	@echo "  integration-test - Run integration tests against deployed server (auto-deploy option)"
	@echo "  integration-test-local - Run integration tests against local server"
	@echo ""
	@echo "  === BUILD & DEPLOY ==="
	@echo "  build            - Run comprehensive tests then build everything server"
	@echo "  build-rtm        - Run comprehensive tests then build RTM server"
	@echo "  deploy-rtm       - Build and deploy RTM server to Fly.io"
	@echo "  build-debug      - Build the debug proxy binary"
	@echo ""
	@echo "  === SCENARIOS ==="
	@echo "  scenario-test-local - Run scenario tests against local server"
	@echo "  scenario-test-prod - Run scenario tests against production"
	@echo ""
	@echo "  === UTILITIES ==="
	@echo "  clean            - Remove build artifacts"
	@echo "  fmt              - Format code"
	@echo "  vet              - Run go vet"
	@echo "  lint             - Run linter (requires golangci-lint)"
	@echo "  coverage         - Generate test coverage report"
	@echo "  run              - Build and run locally"
	@echo "  dev              - Run with hot reload (requires air)"
